### PR TITLE
750 Verify integrity of `jaqy` on download

### PR DESCRIPTION
**Pull request by edavey**
See [Trello 750](https://trello.com/c/QtuzoLE1/750)

We want to verify that the `jaqy` tool used in Ops has not been maliciously modified.

### CODE REVIEW

**Comment by edavey** [comment]
[ITHC: "Use of Unsupported Third Party Component  (Medium)"](https://trello.com/c/QtuzoLE1/750-ithc-use-of-unsupported-third-party-component-medium)

**Review by tahb — APPROVED** [review]
Worked as expected when I did a local test 👍

**Comment by edavey** [comment]
@pezholio could you take a look at this please Stu?

**Review by pezholio — APPROVED** [review]
LGTM - I think it'd be better long term if we could have some kind of service container, but this is a good short term fix

**Review by Harriethw — APPROVED** [review]
LGTM!

**Pull request merged**
