### PR TITLE
APS-573 Add seed job to remove assessment details

### PR DESCRIPTION
**Pull request by davidatkinsuk**
https://dsdmoj.atlassian.net/browse/APS-573

This is required for a specific assessment in production where we want to remove all elements of the assessment data/document except for ‘sufficient-information-confirm’

### CODE REVIEW

**Comment by edavey** [comment]
👍 do you think it would be prudent to include in this job the creation of an `ApplicationTimelineNote` on the association application to record something along the line of "Assessment details redacted". That would provide an adequate audit event with a timestamp?

**Review by edavey — APPROVED** [review]

**Comment by davidatkinsuk** [comment]
> 👍 do you think it would be prudent to include in this job the creation of an `ApplicationTimelineNote` on the association application to record something along the line of "Assessment details redacted". That would provide an adequate audit event with a timestamp?

I think if we find ourselves using this a lot we could do this? I think there's already a note on the application in this case? I can add if you think we need it?

**Comment by edavey** [comment]
> > 👍 do you think it would be prudent to include in this job the creation of an `ApplicationTimelineNote` on the association application to record something along the line of "Assessment details redacted". That would provide an adequate audit event with a timestamp?
> 
> I think if we find ourselves using this a lot we could do this? I think there's already a note on the application in this case? I can add if you think we need it?

I do feel that these data migrations ought to include some narrative in the associated timeline(s) to aid future / further investigation and debugging.

**Comment by davidatkinsuk** [comment]
> > > 👍 do you think it would be prudent to include in this job the creation of an `ApplicationTimelineNote` on the association application to record something along the line of "Assessment details redacted". That would provide an adequate audit event with a timestamp?
> > 
> > 
> > I think if we find ourselves using this a lot we could do this? I think there's already a note on the application in this case? I can add if you think we need it?
> 
> I do feel that these data migrations ought to include some narrative in the associated timeline(s) to aid future / further investigation and debugging.

OK. Given what you've just said on the standup i'm going to rename the seed job to RedactAssessment too

**Review by edavey — APPROVED** [review]
👍 nice, thks!

**Pull request merged**
