### PR TITLE
Revert "Merge pull request #892 from ministryofjustice/NN-5366"

### PR DESCRIPTION
**Pull request by tahb**
# Context 

We used to use the Prisons API for this and were asked [to move to the newer Adjudications API](https://github.com/ministryofjustice/hmpps-approved-premises-api/pull/892/files). We've now had a request to revert this change so we're once again using the Prisons API.

N.b When the original change when in it broke dev and the API deployment pipeline because of client configuration. We should be careful when changing this back to avoid a repeat.

[There has been a previous attempt to do this](https://github.com/ministryofjustice/hmpps-approved-premises-api/pull/1380/) however when running locally we got a 500 after a rebase atop main. There was also lots of Adjudication API knowledge left in that we want to remove until we actually need it and a few minor differences between the original. 

# Changes in this PR

This pull request takes the approach of reverting the original merge commit, so we go back to exactly how we were before when using the Prisons API, and works through the dozen or so conflicts.

The conflicts were reasonably straightforward. Mostly concerned with the more recent introductions of `PersonSummaryInfoResult`, `ApDeliusContextApiClient`, `ApOASysContextApiClient` and getting the prison timelines.

Auto-generated: This reverts commit d1d87d34002060f4fa3d498f848d9ccc92ac2660, reversing changes made to c57c22634bbfedda715f2af0a72c0ca2d986c506.

## Before

dev-adjudications

## After 

There is a difference in the adjudication data coming back for the same POP `/api/offenders/A1234AI/adjudications`. Presumably this test data is just different between Prisons API dev and Adjudications API dev. 

dev-adjuciations-after-my-revert

### CODE REVIEW

**Comment by timoj58** [comment]
as per slack, the difference in the results, is due to the local setup.  The adjudications data comes from wiremock, whereas the prison api data is coming from you local image.

**Comment by tahb** [comment]
Here's a screenshot of Prison test adjudication data coming out of CAS3 in dev for CRN X349420. During the release of this change we should test that this page still pulls the same data, as well as CAS1.

@edavey @davidatkinsuk @danlivings-dxw could I ask for your support in both official code review for this PR and in testing CAS1 locally and in dev please?

Screenshot 2024-02-09 at 12-33-13 Adjudications - Transitional Accommodation (CAS3)

**Comment by edavey** [comment]
This has been tested locally via the CAS1 front-end. We can observe that the adjudications are persisted in:

The work-in-progress questionnaire (`applications.data`):

```json
"adjudications": [
        {
          "id": -3002,
          "reportedAt": "2019-10-25T00:05:00Z",
          "establishment": "Brixton",
          "offenceDescription": "Fails to comply with any condition upon which he is temporarily released under rule 9 - failure to comply with conditions of temp release",
          "hearingHeld": false,
          "finding": null
        },
        {
          "id": -3001,
          "reportedAt": "2019-09-25T00:04:00Z",
          "establishment": "Leeds",
          "offenceDescription": "Fails to comply with any condition upon which he is temporarily released under rule 9 - failure to comply with conditions of temp release",
          "hearingHeld": false,
          "finding": null
        },
        {
          "id": -3,
          "reportedAt": "2019-08-25T00:03:00Z",
          "establishment": "Moorland",
          "offenceDescription": "Detains any person against his will - detention against will of staff (not prison offr)",
          "hearingHeld": true,
          "finding": "PROVED"
        }
      ],

```

and in the finalised read-only `document`:

```json
"Adjudications": [
        {
          "Adjudication number": -3002,
          "Report date and time": "25 Oct 2019, 01:05",
          "Establishment": "Brixton",
          "Offence description": "Fails to comply with any condition upon which he is temporarily released under rule 9 - failure to comply with conditions of temp release",
          "Finding": ""
        },
        {
          "Adjudication number": -3001,
          "Report date and time": "25 Sep 2019, 01:04",
          "Establishment": "Leeds",
          "Offence description": "Fails to comply with any condition upon which he is temporarily released under rule 9 - failure to comply with conditions of temp release",
          "Finding": ""
        },
        {
          "Adjudication number": -3,
          "Report date and time": "25 Aug 2019, 01:03",
          "Establishment": "Moorland",
          "Offence description": "Detains any person against his will - detention against will of staff (not prison offr)",
          "Finding": "Proved"
        }
      ]
```

**Comment by edavey** [comment]
We can see the adjudications rendered in a read-only view of the submitted application:

adjudications_rendered_in_submitted_app

**Review by davidatkinsuk — APPROVED** [review]
I've compared the commit being reverted to this PR and it looks good to me 👍

**Pull request merged**
