### PR TITLE
CAS-365 - Spring Boot Upgrade, No Formatting Change

### PR DESCRIPTION
**Pull request by davidatkinsuk**
Ref: [https://dsdmoj.atlassian.net/browse/CAS-365](https://dsdmoj.atlassian.net/browse/CAS-365)

Accommodation Premises API is currently relying on an outdated version of sprint boot. We need to update/upgrade sprint boot library to the latest version to unblock SAR work

This PR upgrades Spring boot upgrade from 2.7.17 to 3.2.5 by upgrading the hmpps gradle-spring-boot library from 4.14.0 to 5.15.6. When this is merged the following should also be merged, upgrading localstack in dev environments

* https://github.com/ministryofjustice/hmpps-approved-premises-tools/pull/76.

Where possible we've fixed incompatibilities in the code base on the main line (i.e. where the change can be safely made against spring boot 2). These changes include, but are not limited to:

* Removed trailing slashes in some integration tests as the trailing slash matching configuration option has been deprecated and its default value set to false-
[Spring Boot 3.0 Migration Guide](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-3.0-Migration-Guide#spring-mvc-and-webflux-url-matching-changes)
* Upgraded to Java 21 (as required by Hmpps Spring Boot SQS plugin 3.0 upgrade) -
[hmpps-spring-boot-sqs: main](https://github.com/ministryofjustice/hmpps-spring-boot-sqs/tree/main?tab=readme-ov-file#hmpps-spring-boot-sqs--sns) 
* Updated OpenApi Generator from 5.4.0 to 7.5.0 and set necessary config options (set useSpringBoot 3 to true and enumPropertyNaming to camelCase)-
[Documentation for the kotlin-spring Generator | OpenAPI Generator](https://openapi-generator.tech/docs/generators/kotlin-spring) 
* Updated various SQL Result Classes to use Instant instead of LocalDate where the code was relying on Hibernate to convert from a timestamptz value to a LocalDate value, something that hibernate 6 does not support https://github.com/spring-projects/spring-data-jpa/issues/3105
* Change SQL from = null to is null.
* Replaced Spring HTTPMethod in Redis-cached objects to a custom implementation that is unmarshalleable (the version of HTTPMethod in spring boot 3 can't be unmarshalled)

**Testing Notes**

See https://dsdmoj.atlassian.net/wiki/spaces/AP/pages/5012160669/API+Major+Release+Checklist

**Main changes:**

* Renamed all javax packages to jakarta -
[Spring Boot 3.0 Migration Guide](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-3.0-Migration-Guide#jakarta-ee) 
* Updated Redis configuration properties to use spring.data prefix -
[Spring Boot 3.0 Migration Guide](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-3.0-Migration-Guide#redis-properties). This affected helm configuration
* Upgraded Redis instance used for integration testing to 7.2.5
* Upgraded Local stack instance used for integration testing to 3.4.0
* Updated problem-spring-web-starter from 0.27.0 to 0.29.1 - Spring Framework 6 (Spring Boot 3)
* Updated HMPPS Spring Boot SQS plugin (hmpps-sqs-spring-boot-starter) from 1.3.1 to 3.1.3 to target Spring boot 3 -
[ministryofjustice/hmpps-spring-boot-sqs](https://github.com/ministryofjustice/hmpps-spring-boot-sqs).
**  This required an upgrade to the latest version of Localstack
** Change SnsDomainEventListener to use @SqsListener instead of @JmsListener -
[hmpps-spring-boot-sqs/README.md at main · ministryofjustice/hmpps-spring-boot-sqs](https://github.com/ministryofjustice/hmpps-spring-boot-sqs/blob/main/README.md#sqsmessagelistenercontainerfactory) 
** Update SNS clients to use AWS V2 Client instead of V1
* Change authentication method to client_secret_basic in tests
* Replace SQL update with JPA .save() to update data json
* Changed usages of javax.sql.Timestamp to Instant for any query results mapped by Spring Data
* Hibernate Types changed to Hypersistence Utils e.g. `com.vladmihalcea.hibernate.type.json.JsonType` changed to `io.hypersistence.utils.hibernate.type.json.JsonType`
 and dependency updated.  See: https://vladmihalcea.com/hibernate-types-hypersistence-utils/
* Updated dialect from `org.hibernate.spatial.dialect.postgis.PostgisDialect` to `org.hibernate.dialect.PostgreSQLDialect` since spatial dialects are deprecated and no longer supported.
https://docs.jboss.org/hibernate/orm/6.0/migration-guide/migration-guide.html#_dialects
* Removed usage of enums as spring data query params. It's not clear why but the SPEL expressions used to convert enums into strings within the queries no longer worked and led to errors. To work around this string equivalent's of the enums are passed in as parameters

### CODE REVIEW

**Comment by danhumphreys-moj** [comment]
e2e tests have been run against this feature branch in CircleCI: https://app.circleci.com/pipelines/github/ministryofjustice/hmpps-approved-premises-api/18331/workflows/887482d5-5b50-441a-b6f3-c12d927a8a03

**Comment by davidatkinsuk** [comment]
This work was taken from this PR -> https://github.com/ministryofjustice/hmpps-approved-premises-api/pull/1961 which includes various conversations that provide context to this PR.

**Comment by davidatkinsuk** [comment]
Tested in pre-prod, see https://dsdmoj.atlassian.net/wiki/spaces/AP/pages/5024809187/Spring+3+upgrade+Checklist

**Review by danhumphreys-moj — APPROVED** [review]
Spring boot 3 upgrade checklist: https://dsdmoj.atlassian.net/wiki/spaces/AP/pages/5024809187/Spring+3+upgrade+Checklist

**Pull request merged**
